language: java



jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
 
script:  
  - jdk_switcher use oraclejdk8
  - test/Entity/PlayerTest.java
  - jdk_switcher use openjdk8
  - test/Entity/PlayerTest.java